version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: sdoc
    versions:
    - 2.0.3
    - 2.0.4
  - dependency-name: loofah
    versions:
    - 2.9.0
